version: '3'
networks:
  appnetwork:
    driver: bridge
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: taoanhpro
      MYSQL_PASSWORD: taoanhpro
      MYSQL_DATABASE: taoanhpro
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - appnetwork
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ../:/var/www/html
    depends_on:
     - mysql
    networks:
      - appnetwork
  nginx:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../:/var/www/html
    depends_on:
      - php
      - mysql
    networks:
      - appnetwork
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - appnetwork
